### ISSUE TITLE
Python is missing from language list

### ISSUE THREAD

**Issue by michalmo** [BaptisteRoseau/zed-typos#1]
Was trying to work out what was wrong with my config until i realized it only wasn't working in python files, and that Python is missing from the languages list https://github.com/BaptisteRoseau/zed-typos/blob/main/extension.toml#L11

**Comment by BaptisteRoseau** [comment]
Thank you for pointing it out.

I will add it right now. Unfortunately I did not find any way to enable the plugin in all file types for Zed extensions.
While waiting for version 0.0.2 in Zed's extension manager you can clone this repository, add "Python" in the list of supported languages and install it as a dev extension.

Edit: It has been merged on Zed's end so you can install the new version from the marketplace.

**Comment by BaptisteRoseau** [comment]
Ok I made a pull request [here](https://github.com/zed-industries/extensions/pull/1475) to update the extension, and added other Zed supported languages to the list (including Python).

Let me know if your problem is fixed so that we can close this issue.

**Comment by BaptisteRoseau** [comment]
I just confirmed it works with Python files, I'm closing the issue.

**Comment by michalmo** [comment]
Confirmed too, thanks!
