### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by yodatak** [BaptisteRoseau/zed-typos#2]
Hello i use this extentions on linux and i test on my windows build and i got this error

Failed to run typos lsp
Language server error: typos

failed to spawn command. path: "C:\\Users\\yodatak\\AppData\\Local\\Zed\\extensions\\work\\typos\\typos-lsp-v0.1.27\\typos-lsp", working directory: "C:\\Users\\yodatak\\Downloads\\wsl2-main.tar\\wsl2-gadex-main", args: []
-- stderr--

**Comment by BaptisteRoseau** [comment]
@yodatak I will look into it. Can you tell me if you find typos' directory and/or binary inside "C:\Users\yodatak\AppData\Local\Zed\extensions\work" and it's location ?

**Comment by BaptisteRoseau** [comment]
The path to the binary from the Windows archives in https://github.com/tekumara/typos-lsp/releases differs from the Mac and Linux one.
This was fixed and tested.

Awaiting to be merged: https://github.com/zed-industries/extensions/pull/1541

**Comment by yodatak** [comment]
Sorry to my absence i use manly linux only windows at work
